name: Laravel CI/CD to Shared Hosting via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Shared Hosting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Buat file .env
      run: |
        echo "APP_ENV=production" > .env
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_TIMEZONE=UTC" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "BCRYPT_ROUNDS=12" >> .env
        echo "LOG_CHANNEL=stack" >> .env
        echo "LOG_STACK=single" >> .env
        echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
        echo "LOG_LEVEL=debug" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "SESSION_DRIVER=database" >> .env
        echo "SESSION_LIFETIME=120" >> .env
        echo "SESSION_ENCRYPT=false" >> .env
        echo "SESSION_PATH=/" >> .env
        echo "SESSION_DOMAIN=null" >> .env
        echo "BROADCAST_CONNECTION=log" >> .env
        echo "FILESYSTEM_DISK=local" >> .env
        echo "QUEUE_CONNECTION=database" >> .env
        echo "CACHE_STORE=database" >> .env

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./
        server-dir: ./ # ganti sesuai folder Laravel kamu di hosting
        exclude: |
          .git/**
          **/.git/**
          node_modules/**
          tests/**
          vendor/**
          README.md
          .env
          .github/**

    - name: Run Migrations via Webhook
      run: curl "${{ secrets.DEPLOY_URL }}"
